create table restaurants (
  id int generated by default as identity not null primary key,
  name text not null,
  address_line1 text,
  address_line2 text not null,
  address_line3 text,
  address_line4 text,
  postcode text not null,
  latitude double precision not null,
  longitude double precision not null,
  is_active boolean default true,
  business_type text,
  created timestamptz default now(),
  updated timestamptz default now()
);

---- create above / drop below ----

drop table if exists restaurants;
