-- name: CreateFHRSRawData :batchexec
insert into fhrs_raw_data (
    fhrs_id,
    local_authority_business_id,
    business_name,
    business_type,
    business_type_id,
    address_line1,
    address_line2,
    address_line3,
    postcode,
    rating_value,
    rating_key,
    rating_date,
    local_authority_code,
    local_authority_name,
    local_authority_website,
    local_authority_email,
    scheme_type,
    new_rating_pending,
    longitude,
    latitude
  )
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20
  ) on conflict (fhrs_id) do
update
set local_authority_business_id = excluded.local_authority_business_id,
  business_name = excluded.business_name,
  business_type = excluded.business_type,
  business_type_id = excluded.business_type_id,
  address_line1 = excluded.address_line1,
  address_line2 = excluded.address_line2,
  address_line3 = excluded.address_line3,
  postcode = excluded.postcode,
  rating_value = excluded.rating_value,
  rating_key = excluded.rating_key,
  rating_date = excluded.rating_date,
  local_authority_code = excluded.local_authority_code,
  local_authority_name = excluded.local_authority_name,
  local_authority_website = excluded.local_authority_website,
  local_authority_email = excluded.local_authority_email,
  scheme_type = excluded.scheme_type,
  new_rating_pending = excluded.new_rating_pending,
  longitude = excluded.longitude,
  latitude = excluded.latitude;
