// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateFHRSRawData(ctx context.Context, arg []CreateFHRSRawDataParams) *CreateFHRSRawDataBatchResults
	GetNearestRestaurants(ctx context.Context, arg GetNearestRestaurantsParams) ([]GetNearestRestaurantsRow, error)
	SearchRestaurants(ctx context.Context, arg SearchRestaurantsParams) ([]SearchRestaurantsRow, error)
}

var _ Querier = (*Queries)(nil)
